local M = {}

local HEADER_STRING =
  "Auto-generated by snippet-converter.nvim (https://github.com/smjonas/snippet-converter.nvim)"

M.snippet_strings_to_lines = function(snippets_ptr, header_comment_chars)
  -- Add header
  if header_comment_chars ~= nil then
    table.insert(snippets_ptr, 1, header_comment_chars .. HEADER_STRING)
  end

  local len = #snippets_ptr
  local total_len = 0

  local snippet_lines = {}
  local cur_snippet_lines
  for i = 1, len do
    if i ~= len then
      -- Append "\n" to every snippet except the last one
      snippets_ptr[i] = string.format("%s\n", snippets_ptr[i])
    end
    -- Replace "\n" with new line
    cur_snippet_lines = vim.fn.split(snippets_ptr[i], "\n", true)
    for j = 1, #cur_snippet_lines do
      snippet_lines[j + total_len] = cur_snippet_lines[j]
    end
    total_len = total_len + #cur_snippet_lines
  end
  return snippet_lines
end

return M
