name: Generate docs

on:
  push:
    branches: [docs]

jobs:
  gen_docs:
    runs-on: ubuntu-latest
    name: Generate docs with panvimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: snippet-converter
          description: "Convert snippets to the format of your choice"
          pandoc: doc/documentation.md
          version: "NVIM v0.7"
          dedupsubheadings: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
